using Barbearia.Domain.Entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Barbearia.Infrastructure.Persistencia.Configuracoes;

public class UsuarioConfiguration : IEntityTypeConfiguration<Usuario>
{
    public void Configure(EntityTypeBuilder<Usuario> builder)
    {
        // BIGINT GENERATED ALWAYS AS IDENTITY no 01_schema.sql — o padrão
        // do Npgsql para uma migration nova seria "GENERATED BY DEFAULT",
        // então precisamos ser explícitos pra bater com o que já existe.
        builder.Property(u => u.Id).UseIdentityAlwaysColumn();

        // criado_em/atualizado_em são gerados pelo banco (DEFAULT now() e
        // a trigger atualizar_timestamp() — ver 01_schema.sql), nunca
        // pelo C#. ValueGeneratedOnAdd/OnAddOrUpdate diz ao EF Core "não
        // escreva isso no INSERT/UPDATE, só leia de volta o que o banco
        // calculou" (via RETURNING, que o Npgsql já faz automaticamente).
        builder.Property(u => u.CriadoEm).HasDefaultValueSql("now()").ValueGeneratedOnAdd();
        builder.Property(u => u.AtualizadoEm).HasDefaultValueSql("now()").ValueGeneratedOnAddOrUpdate();

        builder.HasIndex(u => u.Email).IsUnique();
    }
}
